stages:
    - validate

markdownlint: 
    stage: validate
    image: 
        name: ruby:apline
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
    script:
        - mdl --style all --warnings .
