stages:
    - validate
    - generate
    - deploy

markdown:
    only:
        - branches
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
    script:
        - mdl .
    allow_failure: true

generate_pages:
    only:
        - external_pull_requests
    except: 
        - branches
    stage: generate
    image:
        name: monachus/hugo
    before_script:
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
    script:
        - echo "Generate pages..."
    
deploy_staging:
    only:
        - external_pull_requests
    except: 
        - branches
    stage: deploy
    image:
        name: golang:alpine
    before_script:
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
    script:
        - echo "Deploying to staging..."
