stages:
    - validate
    - generate

markdown:
    only:
        - master
        - merge_requests
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
    script:
        - mdl .
    allow_failure: true

generate_pages:
    only:
        - master
        - merge_requests
    stage: generate
    image:
        name: monachus/hugo
    script:
        - echo "Generate pages..."
    