stages:
    - validate
    - generate
    - deploy

markdown:
    rules:
        - if: '$CI_EXTERNAL_PULL_REQUEST_IID == null && $CI_COMMIT_BRANCH != "master"'
        - if: '$CI_EXTERNAL_PULL_REQUEST_IID == null'
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
        - echo $CI_COMMIT_BRANCH
    script:
        - mdl .
    allow_failure: true

generate_pages:
    rules:
        - if: '$CI_EXTERNAL_PULL_REQUEST_IID'
    stage: generate
    image:
        name: monachus/hugo
    before_script:
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
    script:
        - echo "Generate pages..."
    
deploy_staging:
    rules:
        - if: '$CI_EXTERNAL_PULL_REQUEST_IID'
    stage: deploy
    image:
        name: golang:alpine
    before_script:
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
    script:
        - echo "Deploying to staging..."
