stages:
    - validate
    - generate

markdown:
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
    script:
        - mdl --style all --warnings .
    allow_failure: true

pages:
    stage: generate
    image:
        name: monachus/hugo
    script:
        - echo "Generate pages..."
    