stages:
    - validate
    - generate
    - deploy

markdown:
    rules:
        - if: $CI_EXTERNAL_PULL_REQUEST_IID == ''
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
        - echo $CI_EXTERNAL_PULL_REQUEST_IID
    script:
        - mdl .
    allow_failure: true

generate_pages:
    only:
        - external_pull_request
    except: 
        - branches
    stage: generate
    image:
        name: monachus/hugo
    script:
        - echo "Generate pages..."
    
deploy_staging:
    only:
        - external_pull_request
    except: 
        - branches
    stage: deploy
    image:
        name: golang:alpine
    script:
        - echo "Deploying to staging..."
