stages:
    - validate
    - generate
    - deploy

markdown:
    only:
        - master
        - external_pull_requests
    stage: validate
    image: 
        name: ruby:alpine
        entrypoint: [""]
    before_script:
        - gem install mdl
        - mdl --version
    script:
        - mdl .
    allow_failure: true

generate_pages:
    only:
        - external_pull_requests
    stage: generate
    image:
        name: monachus/hugo
    script:
        - echo "Generate pages..."
    
deploy_staging:
    only:
        - external_pull_requests
    stage: deploy
    image:
        name: go:alpine
    script:
        - echo "Deploying to staging..."
